"""
Cross-platform polyfit installer.

  macOS   → polyfit.app bundle         (default: ~/Applications)
  Linux   → ~/.local/bin/polyfit        + ~/.local/share/applications/polyfit.desktop
  Windows → polyfit.bat in project dir  + Desktop shortcut via PowerShell

Usage
-----
    python create_app.py                 # full install, default destination
    python create_app.py /custom/path    # macOS: custom .app destination
    python create_app.py --skip-pip      # skip  pip install -e .
    python create_app.py --uninstall     # remove installed files + pip uninstall
"""

import argparse
import os
import platform
import shutil
import stat
import subprocess
import sys
import textwrap

# ---------------------------------------------------------------------------

SYSTEM       = platform.system()          # 'Darwin', 'Linux', 'Windows'
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
PYTHON       = sys.executable
APP_NAME     = "polyfit"
VERSION      = "1.0"

_TTY = sys.stdout.isatty()
def _g(s): return f"\033[32m{s}\033[0m" if _TTY else s   # green
def _b(s): return f"\033[1m{s}\033[0m"  if _TTY else s   # bold
def _r(s): return f"\033[31m{s}\033[0m" if _TTY else s   # red
def _y(s): return f"\033[33m{s}\033[0m" if _TTY else s   # yellow


def step(msg: str) -> None:
    print(f"\n{_b('▸')} {msg}")


# ---------------------------------------------------------------------------
# Shared pip steps
# ---------------------------------------------------------------------------

def pip_install() -> None:
    step("Installing Python package  (pip install -e .)")
    try:
        subprocess.check_call(
            [PYTHON, "-m", "pip", "install", "-e", "."],
            cwd=PROJECT_ROOT,
        )
    except subprocess.CalledProcessError as exc:
        print(_r(f"\n  pip install failed (exit {exc.returncode})."))
        print("  Fix the error above, or re-run with --skip-pip to skip this step.")
        sys.exit(1)


def pip_uninstall() -> None:
    step(f"Removing Python package  (pip uninstall {APP_NAME})")
    subprocess.call([PYTHON, "-m", "pip", "uninstall", "-y", APP_NAME])


# ---------------------------------------------------------------------------
# macOS
# ---------------------------------------------------------------------------

def _macos_app_path(dest_dir: str) -> str:
    return os.path.join(os.path.expanduser(dest_dir), f"{APP_NAME}.app")


def build_macos(dest_dir: str) -> str:
    app_path  = _macos_app_path(dest_dir)
    macos_dir = os.path.join(app_path, "Contents", "MacOS")

    step(f"Building  {APP_NAME}.app  →  {app_path}")
    if os.path.exists(app_path):
        print(f"  Removing previous installation at {app_path}")
        shutil.rmtree(app_path)
    os.makedirs(macos_dir, exist_ok=True)

    plist = textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key><string>{APP_NAME}</string>
            <key>CFBundleIdentifier</key><string>com.polyfit.gui</string>
            <key>CFBundleName</key><string>{APP_NAME}</string>
            <key>CFBundleDisplayName</key><string>polyfit</string>
            <key>CFBundleVersion</key><string>{VERSION}</string>
            <key>CFBundleShortVersionString</key><string>{VERSION}</string>
            <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
            <key>CFBundlePackageType</key><string>APPL</string>
            <key>NSHighResolutionCapable</key><true/>
            <key>LSMinimumSystemVersion</key><string>10.13</string>
        </dict>
        </plist>
    """)

    launcher_sh = textwrap.dedent(f"""\
        #!/bin/bash
        # Auto-generated by create_app.py — re-run to regenerate after moving the project.
        cd "{PROJECT_ROOT}"
        exec "{PYTHON}" "{PROJECT_ROOT}/gui.py"
    """)

    with open(os.path.join(app_path, "Contents", "Info.plist"), "w") as fh:
        fh.write(plist)

    launcher = os.path.join(macos_dir, APP_NAME)
    with open(launcher, "w") as fh:
        fh.write(launcher_sh)
    os.chmod(launcher, os.stat(launcher).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return app_path


def uninstall_macos(dest_dir: str) -> None:
    app_path = _macos_app_path(dest_dir)
    if os.path.exists(app_path):
        step(f"Removing {app_path}")
        shutil.rmtree(app_path)
    else:
        print(f"  {app_path} not found, skipping.")


# ---------------------------------------------------------------------------
# Linux
# ---------------------------------------------------------------------------

_LINUX_BIN     = os.path.expanduser("~/.local/bin")
_LINUX_APPS    = os.path.expanduser("~/.local/share/applications")
_LINUX_LAUNCHER = os.path.join(_LINUX_BIN,  APP_NAME)
_LINUX_DESKTOP  = os.path.join(_LINUX_APPS, f"{APP_NAME}.desktop")


def build_linux() -> tuple:
    os.makedirs(_LINUX_BIN,  exist_ok=True)
    os.makedirs(_LINUX_APPS, exist_ok=True)

    launcher_sh = textwrap.dedent(f"""\
        #!/bin/bash
        # Auto-generated by create_app.py — re-run to regenerate after moving the project.
        cd "{PROJECT_ROOT}"
        exec "{PYTHON}" "{PROJECT_ROOT}/gui.py"
    """)

    desktop_entry = textwrap.dedent(f"""\
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=polyfit
        Comment=Fit copolymerization reactivity ratios (Reischke, 2023)
        Exec={PYTHON} {PROJECT_ROOT}/gui.py
        Icon=
        Terminal=false
        Categories=Science;Education;
        StartupNotify=false
    """)

    step(f"Writing launcher script  →  {_LINUX_LAUNCHER}")
    with open(_LINUX_LAUNCHER, "w") as fh:
        fh.write(launcher_sh)
    os.chmod(_LINUX_LAUNCHER,
             os.stat(_LINUX_LAUNCHER).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    step(f"Writing desktop entry  →  {_LINUX_DESKTOP}")
    with open(_LINUX_DESKTOP, "w") as fh:
        fh.write(desktop_entry)
    os.chmod(_LINUX_DESKTOP,
             os.stat(_LINUX_DESKTOP).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return _LINUX_LAUNCHER, _LINUX_DESKTOP


def uninstall_linux() -> None:
    for path in (_LINUX_LAUNCHER, _LINUX_DESKTOP):
        if os.path.exists(path):
            step(f"Removing {path}")
            os.remove(path)
        else:
            print(f"  {path} not found, skipping.")


# ---------------------------------------------------------------------------
# Windows
# ---------------------------------------------------------------------------

_WIN_BAT      = os.path.join(PROJECT_ROOT, f"{APP_NAME}.bat")
_WIN_SHORTCUT = os.path.join(os.path.expanduser("~"), "Desktop", f"{APP_NAME}.lnk")


def build_windows() -> str:
    gui_py = os.path.join(PROJECT_ROOT, "gui.py")

    # .bat launcher — CRLF line endings required on Windows
    bat = (
        f"@echo off\r\n"
        f"cd /d \"{PROJECT_ROOT}\"\r\n"
        f"\"{PYTHON}\" \"{gui_py}\"\r\n"
    )
    step(f"Writing launcher  →  {_WIN_BAT}")
    with open(_WIN_BAT, "w") as fh:
        fh.write(bat)

    # Desktop shortcut via PowerShell WScript.Shell (no third-party deps needed)
    step(f"Creating Desktop shortcut  →  {_WIN_SHORTCUT}")
    ps = (
        f"$ws = New-Object -ComObject WScript.Shell; "
        f"$sc = $ws.CreateShortcut('{_WIN_SHORTCUT}'); "
        f"$sc.TargetPath = '{PYTHON}'; "
        f"$sc.Arguments = '\"{gui_py}\"'; "
        f"$sc.WorkingDirectory = '{PROJECT_ROOT}'; "
        f"$sc.Description = 'polyfit GUI'; "
        f"$sc.Save()"
    )
    try:
        subprocess.check_call(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps],
            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(_y(f"  Warning: could not create Desktop shortcut ({exc})"))
        print(f"  You can still launch polyfit by double-clicking:\n    {_WIN_BAT}")

    return _WIN_BAT


def uninstall_windows() -> None:
    for path in (_WIN_BAT, _WIN_SHORTCUT):
        if os.path.exists(path):
            step(f"Removing {path}")
            os.remove(path)
        else:
            print(f"  {path} not found, skipping.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install or uninstall polyfit as a launchable application.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            macOS:   creates polyfit.app             (default: ~/Applications)
            Linux:   installs to ~/.local/bin        + ~/.local/share/applications
            Windows: creates polyfit.bat in project  + Desktop shortcut
        """),
    )
    parser.add_argument(
        "dest", nargs="?", default="~/Applications",
        help="destination folder — macOS only (default: ~/Applications)",
    )
    parser.add_argument(
        "--skip-pip", action="store_true",
        help="skip  pip install -e .",
    )
    parser.add_argument(
        "--uninstall", action="store_true",
        help="remove all installed files and pip-uninstall the package",
    )
    args = parser.parse_args()

    print(_b(f"\npolyfit installer  —  {SYSTEM}  (Python: {PYTHON})"))
    print(f"Project root: {PROJECT_ROOT}")

    # ── Uninstall path ────────────────────────────────────────────────
    if args.uninstall:
        if SYSTEM == "Darwin":
            uninstall_macos(args.dest)
        elif SYSTEM == "Linux":
            uninstall_linux()
        elif SYSTEM == "Windows":
            uninstall_windows()
        else:
            print(_y(f"  No known install location for platform '{SYSTEM}'."))
        pip_uninstall()
        print(_g("\n✓  Uninstall complete."))
        return

    # ── Install path ──────────────────────────────────────────────────
    if not args.skip_pip:
        pip_install()

    if SYSTEM == "Darwin":
        path = build_macos(args.dest)
        print(_g(f"\n✓  Installed → {path}"))
        print(f"\n  Launch: double-click  {path}  in Finder")
        print(f"  Or from terminal:     open \"{path}\"")
        print(_b("\nNote:") + " macOS may show a Gatekeeper prompt the first time.")
        print("  System Settings → Privacy & Security → Open Anyway")

    elif SYSTEM == "Linux":
        launcher, desktop = build_linux()
        print(_g("\n✓  Installed"))
        print(f"  Launcher:      {launcher}")
        print(f"  Desktop entry: {desktop}")
        print("\n  Launch from terminal:  polyfit")
        print("  Or search for 'polyfit' in your application launcher.")
        print(_y("\n  If the command is not found, add ~/.local/bin to PATH:"))
        print('    echo \'export PATH="$HOME/.local/bin:$PATH"\' >> ~/.bashrc && source ~/.bashrc')

    elif SYSTEM == "Windows":
        bat = build_windows()
        print(_g("\n✓  Installed"))
        print(f"  Launcher:         {bat}")
        print(f"  Desktop shortcut: {_WIN_SHORTCUT}")
        print("\n  Launch: double-click the polyfit shortcut on your Desktop.")
        print(f"  Or run directly:   {bat}")

    else:
        print(_r(f"\n  Platform '{SYSTEM}' is not supported."))
        print("  Run the GUI directly:  python gui.py")
        sys.exit(1)


if __name__ == "__main__":
    main()
